#!/usr/bin/env python3
"""Convert hand-lettered loading art and bake deterministic horizontal dissolves."""
from pathlib import Path
from PIL import Image

root = Path(__file__).resolve().parents[1]
source = root / 'art/loading/loading-text-generated.png'
system = root / 'source/SystemAssets'
frames = root / 'source/resource/loading'
launch = system / 'launchImages'
for folder in (system, frames, launch):
    folder.mkdir(parents=True, exist_ok=True)
image = Image.open(source).convert('L').resize((400, 240), Image.Resampling.LANCZOS)
image = image.point(lambda value: 255 if value >= 128 else 0, mode='1')
image.save(system / 'launchImage.png')
bounds = image.getbbox()
assert bounds, 'Loading artwork is empty'
left, top, right, bottom = bounds
bayer = ((0,8,2,10),(12,4,14,6),(3,11,1,9),(15,7,13,5))
# Fixed spatial thresholds, shared by every frame. Each white pixel switches
# once per transition, with a 28px stippled edge travelling left to right.
band = 28
thresholds = {(x,y): ((x-left) + (bayer[y%4][x%4]+.5)/16*band) / (right-left+band)
              for y in range(top,bottom) for x in range(left,right) if image.getpixel((x,y))}
for index in range(13):
    progress = index / 12
    entering, leaving = Image.new('1',(400,240)), Image.new('1',(400,240))
    for pixel, threshold in thresholds.items():
        entering.putpixel(pixel, int(threshold <= progress))
        leaving.putpixel(pixel, int(threshold > progress))
    entering.save(frames / f'in-table-{index+1}.png')
    leaving.save(frames / f'out-table-{index+1}.png')
    entering.save(launch / f'{index+1}.png')
(root / 'source/loadingAssets.lua').write_text(
    '-- Generated by tools/build_startup_loading.py.\n'
    'LoadingAssets = { frames = 13, duration = .4 }\n')
print(f'Built loading image and 13-frame horizontal dissolves: {frames}')
