#!/usr/bin/env python3
"""Convert rasterized title frames to native 1-bit assets; preserve alpha masks.

First run render_title_frames.cjs, then this script with its output directory.
This is offline rasterization/format conversion of the approved art, not new art.
"""
from pathlib import Path
import sys
from PIL import Image
from build_sprites import BAYER

ROOT = Path(__file__).resolve().parents[1]
RAW = Path(sys.argv[1] if len(sys.argv) > 1 else '/private/tmp/bun-rush-title-frames')
OUTPUT = ROOT / 'source/resource/title'
OUTPUT.mkdir(parents=True, exist_ok=True)


def convert(source, target, transparent=False):
    image = Image.open(source).convert('RGBA')
    assert image.size == (400, 240), (source, image.size)
    gray = image.convert('L')
    mono = Image.new('1', image.size)
    pixels, shades = mono.load(), gray.load()
    for y in range(image.height):
        for x in range(image.width):
            # Solid lettering stays legible; tonal artwork keeps its stipple.
            threshold = 127 if transparent else (BAYER[y % 8][x % 8] + .5) * 255 / 64
            pixels[x, y] = shades[x, y] > threshold
    bounds = (0, 0, 400, 240)
    if transparent:
        alpha = image.getchannel('A').point(lambda value: 255 if value >= 128 else 0)
        bounds = alpha.getbbox()
        assert bounds, source
        mono = mono.convert('RGBA')
        mono.putalpha(alpha)
        mono = mono.crop(bounds)
    mono.save(target)
    return bounds


for index in range(1, 82):
    convert(RAW / f'road-{index:03}.png', OUTPUT / f'road-table-{index}.png')
convert(RAW / 'shutter.png', OUTPUT / 'shutter.png')
title = convert(RAW / 'title.png', OUTPUT / 'title.png', True)
prompt = convert(RAW / 'start.png', OUTPUT / 'prompt.png', True)
# One opaque resting door avoids blending the transparent title every frame.
closed = Image.open(OUTPUT / 'shutter.png').convert('RGBA')
lettering = Image.open(OUTPUT / 'title.png').convert('RGBA')
closed.alpha_composite(lettering, (title[0], title[1]))
closed.convert('1', dither=Image.Dither.NONE).save(OUTPUT / 'closed.png')
(ROOT / 'source/titleAssets.lua').write_text(
    '-- Generated by tools/build_title_assets.py; native pixel bounds.\n'
    'TitleAssets = {\n    roadFPS = 30, roadFrames = 81, roadDuration = 2.7,\n'
    f'    titleX = {title[0]}, titleY = {title[1]},\n'
    f'    promptX = {prompt[0]}, promptY = {prompt[1]},\n'
    '}\n')
print(f'Built 81 monochrome road frames, 3 layers and a cached closed door in {OUTPUT}')
print(f'Title bounds: {title}; prompt bounds: {prompt}')
