-- Generated by tools/build_title_assets.py; native pixel bounds.
TitleAssets = {
    roadFPS = 30, roadFrames = 81, roadDuration = 2.7,
    titleX = 46, titleY = 10,
    promptX = 146, promptY = 214,
}
